### ISSUE TITLE
.env file missing

### ISSUE THREAD

**Issue by allandaly** [testdrivenio/taxi-ng-app#37]
This is an excellent project! Thanks for making this available and all the work behind it. Super useful to me.

I'm not sure if this is intentional or not, but in the master branch you did not commit the .env file in the /server directory, so on the first pull it's not possible to bring up the docker-compose environment.

-Allan

**Comment by ParentJA** [comment]
Hey @allandaly glad you like the course and project! I'm so sorry for the confusion. I think this repo might have an outdated *docker-compose.yml* file. I'll release a course update soon to fix that. In the meantime, take a look at https://github.com/ParentJA/taxi-react-app-part-3 for a more up-to-date version of the *docker-compose.yml*. Let me know if you have anymore questions, thanks!

**Comment by allandaly** [comment]
Thanks for your reply! It's no prob for me to make the .env and bring things up -- just thought you'd want to know. :)
